# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fishackathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fishackathon
  pod 'Charts'
  pod 'Alamofire', '4.5.1'
  pod 'Nuke', '5.2'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'LGButton'
  pod 'KeychainSwift', '~> 10.0'
  pod 'IQKeyboardManagerSwift'

end
